name: pgc-stac-environment
channels:
  - conda-forge
dependencies:
  - pystac-client
  - ipyleaflet
  - stackstac
  - xarray
  - geopandas
  - pandas
  - jupyter
  - ipython
  - geojson
  - pydrive2
  - requests
  - google-api-python-client 
  - google-auth-httplib2 
  - google-auth-oauthlib